name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflows_call:
jobs:
  platform_ci:
    uses: GitFabien/platform-demo-lab1/.github/workflows/jan/ci.yml@main
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run tests
        run: make test
